INSERT INTO pet_types (type)
VALUES
  ('Tiger'),
  ('Lion'),
  ('Fox'),
  ('Turtle'),
  ('Snake'),
  ('Lizard'),
  ('Dragon'),
  ('Griffin'),
  ('Wyvern'),
  ('Pegasus'),
  ('Phoenix'),
  ('Basilisk'),
  ('Hippogriff'),
  ('Niffler'), 
  ('Bowtruckle'), 
  ('Thunderbird'), 
  ('Occamy');
